name: Fetch TOI RSS and Create Blog Posts

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir feedparser pyyaml || (echo "Failed to install dependencies"; exit 1)

      - name: Fetch RSS and Generate Posts
        run: |
          python scripts/rss_to_posts.py || (echo "Python script failed"; exit 1)
        env:
          RSS_FEED_URL: "https://timesofindia.indiatimes.com/rssfeeds/4719161.cms"

      - name: Commit New Posts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _posts/*
          git commit -m "Add new blog posts from TOI RSS" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:$GITHUB_REF_NAME
