name: Fetch TOI RSS and Create Blog Posts

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install --no-cache-dir feedparser pyyaml || (echo "Failed to install dependencies"; exit 1)

      - name: Fetch RSS and Generate Posts
        run: |
          python scripts/rss_to_posts.py || (echo "Python script failed"; exit 1)
        env:
          RSS_FEED_URL: "https://timesofindia.indiatimes.com/rssfeeds/4719161.cms"

      - name: Set Up Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll and Build Site
        run: |
          gem install jekyll
          jekyll build --destination _site || (echo "Jekyll build failed"; exit 1)

      - name: Deploy to Main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Clear root except for _site
          find . -maxdepth 1 -not -name '_site' -not -name '.' -not -name '..' -exec rm -rf {} +
          # Move _site contents to root
          mv _site/* .
          rm -rf _site
          git add .
          git commit -m "Deploy updated blog posts" || echo "No changes to commit"
          git push origin main
